export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  Afghanistan: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad', 'Kunduz'],
  Albania: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Elbasan'],
  Algeria: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida'],
  Argentina: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Tucumán'],
  Armenia: ['Yerevan', 'Gyumri', 'Vanadzor'],
  Australia: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra', 'Gold Coast', 'Hobart'],
  Austria: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'],
  Azerbaijan: ['Baku', 'Ganja', 'Sumqayit'],
  Bahrain: ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'],
  Bangladesh: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Gazipur'],
  Belarus: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest'],
  Belgium: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges'],
  Bhutan: ['Thimphu', 'Phuntsholing', 'Paro', 'Punakha'],
  Bolivia: ['La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre', 'El Alto'],
  'Bosnia and Herzegovina': ['Sarajevo', 'Banja Luka', 'Mostar', 'Tuzla'],
  Brazil: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Curitiba', 'Recife'],
  Brunei: ['Bandar Seri Begawan', 'Kuala Belait', 'Seria'],
  Bulgaria: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse'],
  Cambodia: ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'],
  Cameroon: ['Yaoundé', 'Douala', 'Garoua', 'Bamenda'],
  Canada: ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Edmonton', 'Winnipeg', 'Quebec City'],
  Chile: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta'],
  China: ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xi’an', 'Nanjing'],
  Colombia: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'],
  Croatia: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Dubrovnik'],
  Cyprus: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'],
  'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Plzeň'],
  Denmark: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'],
  Egypt: ['Cairo', 'Alexandria', 'Giza', 'Sharm El Sheikh', 'Luxor', 'Aswan'],
  Estonia: ['Tallinn', 'Tartu', 'Narva', 'Pärnu'],
  Ethiopia: ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar'],
  Finland: ['Helsinki', 'Espoo', 'Tampere', 'Oulu', 'Turku'],
  France: ['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Bordeaux', 'Lille'],
  Georgia: ['Tbilisi', 'Batumi', 'Kutaisi'],
  Germany: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dortmund'],
  Ghana: ['Accra', 'Kumasi', 'Tamale', 'Cape Coast'],
  Greece: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion'],
  'Hong Kong': ['Hong Kong', 'Kowloon', 'Tsuen Wan'],
  Hungary: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs'],
  Iceland: ['Reykjavík', 'Kópavogur', 'Akureyri'],
  India: [
    'New Delhi',
    'Mumbai',
    'Bengaluru',
    'Hyderabad',
    'Chennai',
    'Kolkata',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Lucknow',
    'Chandigarh',
  ],
  Indonesia: ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Bekasi', 'Depok', 'Semarang', 'Makassar', 'Bali (Denpasar)'],
  Iran: ['Tehran', 'Mashhad', 'Isfahan', 'Shiraz', 'Tabriz', 'Karaj'],
  Iraq: ['Baghdad', 'Basra', 'Erbil', 'Mosul', 'Najaf', 'Sulaymaniyah'],
  Ireland: ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford'],
  Italy: ['Rome', 'Milan', 'Naples', 'Turin', 'Florence', 'Venice', 'Bologna', 'Palermo', 'Genoa'],
  Japan: ['Tokyo', 'Osaka', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kyoto', 'Kobe', 'Hiroshima'],
  Jordan: ['Amman', 'Zarqa', 'Irbid', 'Aqaba'],
  Kazakhstan: ['Almaty', 'Astana', 'Shymkent', 'Karaganda'],
  Kenya: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
  Kuwait: ['Kuwait City', 'Hawalli', 'Salmiya', 'Al Ahmadi', 'Jahra'],
  Kyrgyzstan: ['Bishkek', 'Osh', 'Jalal-Abad'],
  Latvia: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava'],
  Lebanon: ['Beirut', 'Tripoli', 'Sidon', 'Zahle', 'Byblos'],
  Libya: ['Tripoli', 'Benghazi', 'Misrata', 'Bayda'],
  Lithuania: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai'],
  Luxembourg: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange'],
  Malaysia: ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Ipoh', 'Shah Alam', 'Kota Kinabalu', 'Kuching', 'Malacca'],
  Maldives: ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi'],
  Malta: ['Valletta', 'Sliema', 'St. Julian’s', 'Birkirkara'],
  Mexico: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Cancún', 'Mérida'],
  Morocco: ['Casablanca', 'Rabat', 'Marrakesh', 'Fes', 'Tangier', 'Agadir'],
  Nepal: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Bhaktapur'],
  Netherlands: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen'],
  'New Zealand': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Dunedin', 'Tauranga'],
  Nigeria: ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City'],
  Norway: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Tromsø'],
  Oman: ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur'],
  Pakistan: [
    'Islamabad',
    'Rawalpindi',
    'Lahore',
    'Karachi',
    'Faisalabad',
    'Multan',
    'Peshawar',
    'Quetta',
    'Gujranwala',
    'Sialkot',
    'Hyderabad',
    'Sukkur',
    'Bahawalpur',
    'Sargodha',
    'Mardan',
    'Abbottabad',
    'Gujrat',
    'Rahim Yar Khan',
    'Sahiwal',
    'Okara',
  ],
  Palestine: ['Ramallah', 'Gaza', 'Hebron', 'Nablus', 'Bethlehem', 'Jenin'],
  Philippines: ['Manila', 'Quezon City', 'Cebu City', 'Davao City', 'Makati', 'Pasig'],
  Poland: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk'],
  Portugal: ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Faro'],
  Qatar: ['Doha', 'Al Rayyan', 'Al Wakrah', 'Lusail', 'Al Khor'],
  Romania: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Brașov'],
  Russia: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod'],
  'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Taif', 'Abha', 'Tabuk'],
  Serbia: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac'],
  Singapore: ['Singapore'],
  Slovakia: ['Bratislava', 'Košice', 'Prešov', 'Žilina'],
  Slovenia: ['Ljubljana', 'Maribor', 'Celje', 'Koper'],
  'South Africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein'],
  'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon'],
  Spain: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Bilbao', 'Granada'],
  'Sri Lanka': ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo'],
  Sweden: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås'],
  Switzerland: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Lucerne'],
  Syria: ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama'],
  Taiwan: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu'],
  Tajikistan: ['Dushanbe', 'Khujand', 'Bokhtar'],
  Thailand: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Hat Yai', 'Khon Kaen'],
  Tunisia: ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte'],
  Turkey: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Gaziantep', 'Konya', 'Adana'],
  Turkmenistan: ['Ashgabat', 'Turkmenabat', 'Dashoguz'],
  Ukraine: ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Lviv'],
  'United Arab Emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Al Ain'],
  'United Kingdom': [
    'London',
    'Manchester',
    'Birmingham',
    'Leeds',
    'Glasgow',
    'Edinburgh',
    'Liverpool',
    'Bristol',
    'Cardiff',
    'Belfast',
    'Newcastle',
    'Sheffield',
  ],
  'United States': [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Seattle',
    'Denver',
    'Boston',
    'Miami',
    'Atlanta',
    'Washington',
  ],
  Uzbekistan: ['Tashkent', 'Samarkand', 'Bukhara', 'Namangan', 'Andijan'],
  Vietnam: ['Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hai Phong', 'Can Tho', 'Hue'],
  Yemen: ['Sana’a', 'Aden', 'Taiz', 'Hodeidah', 'Ibb'],
};

export function citiesForCountry(country: string): string[] {
  return CITIES_BY_COUNTRY[country] ?? [];
}
